### ISSUE TITLE
rename() python version issue

### ISSUE THREAD

**Issue by pab2163** [cu-psych-computing/cu-psych-comp-tutorial#54]
in the python data cleaning tutorial, rename() syntax needs to be different for different python versions

Some versions should have 
`mydata = mydata.rename({'Personality':'Neuroticism'}, axis="columns")`

Others have
`mydata = mydata.rename(columns = {'Personality':'Neuroticism'})`

Should we make this an explicit part of the lesson, or make this version-proof?

**Comment by monicathieu** [comment]
I only just saw this issue a year late lol. Strong vote to version-proof syntax. But if this is a python2 vs python3 thing, we should be STRONGLY recommending people to use python3, and then we only need to teach that one. Or is this a `pandas` versioning issue?

**Comment by boomsbloom** [comment]
I think I misunderstood this bug, I thought "rename" was called in these two ways in the content. That isn't the case, it's always the first one. 

Both versions work in python 3 (just tested in a new environment). I am going to leave as is because using "axis" is the preferred format according to the pandas docs--all students should be using python 3. We should make this announcement at the beginning of the session.
